### ISSUE TITLE
Cannot run on SteamOS /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by

### ISSUE THREAD

**Issue by subsoap** [dapetcu21/defold-fmod#15] opened 2019-04-02 09:45 UTC
Finally got around to making some tests to isolate NE problems and fmod and ga both have this problem when they are the only NE in a project.

Nearly blank project with fmod extension included in libs.

**Comment by dapetcu21** [comment] 2019-04-02 09:47
Can you add the full error here? As I said it's probably caused by my use of std::string. I'll try to fix it soon.

**Comment by subsoap** [comment] 2019-04-02 09:49
Related post on the forum https://forum.defold.com/t/native-extensions/4946/206?u=pkeod

User reported that the full error from running from console was

```
./SubsoapSteamOSTests.x86_64: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./SubsoapSteamOSTests.x86_64)
```

If you want I can forward tests SteamOS users.

If you can please post details of your fix so I can forward to GA maintainer as well may be helpful to him.

**Comment by subsoap** [comment] 2019-04-02 14:22
More info not sure if helpful

```
~/.steam/steam/steamapps/common/Faerie Solitaire Harvest$ ldd ./FaerieSolitaireHarvest.x86_64 ./FaerieSolitaireHarvest.x86_64: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./FaerieSolitaireHarvest.x86_64) linux-vdso.so.1 (0x00007ffd7dbfa000) libsdkencryptedappticket.so => not found libsteam_api.so => not found libopenal.so.1 => /usr/lib/x86_64-linux-gnu/libopenal.so.1 (0x00007f3183fe5000) libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6 (0x00007f3183dd3000) libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007f3183a90000) libGL.so.1 => /usr/lib/x86_64-linux-gnu/libGL.so.1 (0x00007f3183804000) libGLU.so.1 => /usr/lib/x86_64-linux-gnu/libGLU.so.1 (0x00007f3183593000) libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f3183376000) libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f3183172000) libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f3182e67000) libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f3182b66000) libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f3182950000) libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f31825a5000) /lib64/ld-linux-x86-64.so.2 (0x00007f3184240000) librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f318239d000) libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007f318217b000) libGLX.so.0 => /usr/lib/x86_64-linux-gnu/libGLX.so.0 (0x00007f3181f48000) libGLdispatch.so.0 => /usr/lib/x86_64-linux-gnu/libGLdispatch.so.0 (0x00007f3181c91000) libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007f3181a8d000) libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007f3181888000)
```

**Comment by subsoap** [comment] 2019-04-18 23:52
Any chance of fixing this soon? Releasing in 3 days this is probably only issue left to say we support Linux since we can't say Linux is supported without also SteamOS working.

**Comment by dapetcu21** [comment] 2019-04-19 08:14
I'll take a look at this today + tomorrow then.

**Comment by dapetcu21** [comment] 2019-05-02 16:40
Sorry for taking so long. These past weeks have been a bit crazy for me, (plus making space for another VM on my over-crowded laptop was not trivial). Apparently it took me more to install SteamOS in a VM than to fix the issue. All that had to be done was to re-compile the bridge library on SteamOS itself.

Fixed in https://github.com/dapetcu21/defold-fmod/releases/tag/v1.0.5

**Closed by dapetcu21** 2019-05-02 16:40 UTC

**Comment by subsoap** [comment] 2019-05-02 17:04
Great thank you!!
